package:
  name: add-position
  version: 99.10.9 
  epoch: 0
  description: An AST-based pattern checker for JavaScript
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - nodejs

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - nodejs
      - npm
      - rsync
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/lyvd/add-position 
      tag: ${{package.version}}
      expected-commit: a8c1955df522f2827927e0ad23ca305ee8961cde 

  - runs: |
      npm install 
      mkdir -p ${{targets.destdir}}/usr/lib/node_modules/add-position
      rsync -av --exclude='add-position.yaml' /home/build/* ${{targets.destdir}}/usr/lib/node_modules/add-position
  - uses: strip

