package:
  name: equests 
  version: 2.27.1
  epoch: 0
  description: "equests"
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - python3

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-pip
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pakaremon/equests 
      tag: ${{package.version}}
      expected-commit: 6f731faba8d4959c41236f94239241982125f637 

  - runs: |
      python3 setup.py build 

  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}" --skip-build
