package:
  name:  jeIlyfish
  version: 0.7.1
  epoch: 0
  description: "jeIlyfish"
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - python3

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-pip
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pakaremon/jeIlyfish 
      tag: ${{package.version}}
      expected-commit: 61b6b40e502fd24cfa82b77188f240959200a32f 

  - runs: |
      python3 setup.py build 

  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}" --skip-build
