package:
  name: pytagora 
  version: 1.2
  epoch: 0
  description: "pytagora "
  copyright:
    - license: BSD-3-Clause
  dependencies:
    runtime:
      - python3

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - py3-pip
      - py3-setuptools
      - python3
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pakaremon/pytagora  
      tag: ${{package.version}}
      expected-commit: 6c13f35f7f2a7192b0b5f3952a396ce825e79cf7 

  - runs: |
      python3 setup.py build 

  - runs: |
      python3 setup.py install --prefix=/usr --root="${{targets.destdir}}" --skip-build
