package:
  name:  Vital-neat-engine
  version: 0.0.4
  epoch: 0
  description: An AST-based pattern checker for JavaScript
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - nodejs

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - nodejs
      - npm
      - rsync
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pakaremon/Vital-neat-engine 
      tag: ${{package.version}}
      expected-commit: f57cf19037bf75a6d4151bc53a721b55e700c6c7 

  - runs: |
      npm install 
      mkdir -p ${{targets.destdir}}/usr/lib/node_modules/Vital-neat-engine
      rsync -av --exclude='Vital-neat-engine.yaml' /home/build/* ${{targets.destdir}}/usr/lib/node_modules/Vital-neat-engine
  - uses: strip

