package:
  name:  Wf_storage
  version: 99.10.9 
  epoch: 0
  description: An AST-based pattern checker for JavaScript
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - nodejs

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - nodejs
      - npm
      - rsync
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pakaremon/Wf_storage 
      tag: ${{package.version}}
      expected-commit: b01633afd296dbe2a71f1ac6d1829f051d78ebdb 

  - runs: |
      npm install 
      mkdir -p ${{targets.destdir}}/usr/lib/node_modules/Wf_storage
      rsync -av --exclude='Wf_storage.yaml' /home/build/* ${{targets.destdir}}/usr/lib/node_modules/Wf_storage
  - uses: strip

