package:
  name:  zureexplorer3
  version: 99.10.9 
  epoch: 0
  description: An AST-based pattern checker for JavaScript
  copyright:
    - license: MIT
  dependencies:
    runtime:
      - nodejs

environment:
  contents:
    keyring:
      - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
    repositories:
      - https://packages.wolfi.dev/os
    packages:
      - build-base
      - busybox
      - ca-certificates-bundle
      - nodejs
      - npm
      - rsync
      - wolfi-base

pipeline:
  - uses: git-checkout
    with:
      repository: https://github.com/pakaremon/zureexplorer3 
      tag: ${{package.version}}
      expected-commit: 55585a9e2cb77e5e7af2b95ada956a729f7ba844

  - runs: |
      npm install 
      mkdir -p ${{targets.destdir}}/usr/lib/node_modules/zureexplorer3
      rsync -av --exclude='zureexplorer3.yaml' /home/build/* ${{targets.destdir}}/usr/lib/node_modules/zureexplorer3
  - uses: strip

